import type { PhraseChunk, PhraseTemplate } from '../../src/app/sub-app/phrase-lab/models/phrase.model';

// Transcribed verbatim from docs/superpowers/specs/2026-08-05-phrase-lab-design.md
// Section 8. The spec tables are the source of truth for ids, english, vietnamese,
// phonetic (British IPA), role, and level. Examples for each chunk are derived from
// the same-context template's example sentence or a natural collocation.
//
// Two role reclassifications were required to make every {chunk:role} slot in every
// template resolve to a matching chunk (see REPORT for the spec's internal
// inconsistency and how it was resolved):
//   - day-work-b2-01 "to stay on top of": linker -> opener
//   - day-work-b2-03 "to prioritize the tasks": filler -> linker
//   (the template's own example sentences justify both changes)

export const SEED_CHUNKS: PhraseChunk[] = [
  // ===== 8.1 IT — meeting =====
  {
    id: 'it-meet-b1-01',
    domain: 'it',
    context: 'meeting',
    level: 'B1',
    english: 'as you know',
    vietnamese: 'như bạn đã biết',
    phonetic: '/æz juː nəʊ/',
    role: 'opener',
    examples: [
      { en: 'As you know, we have a tight deadline this sprint.', vi: 'Như bạn đã biết, chúng ta có deadline gấp cho sprint này.' },
    ],
  },
  {
    id: 'it-meet-b1-02',
    domain: 'it',
    context: 'meeting',
    level: 'B1',
    english: 'in my opinion',
    vietnamese: 'theo ý tôi',
    phonetic: '/ɪn maɪ əˈpɪnjən/',
    role: 'opener',
    examples: [
      { en: 'In my opinion, the API is the right place to start.', vi: 'Theo ý tôi, API là chỗ đúng để bắt đầu.' },
    ],
  },
  {
    id: 'it-meet-b1-03',
    domain: 'it',
    context: 'meeting',
    level: 'B1',
    english: "let's move on",
    vietnamese: 'chúng ta chuyển tiếp nhé',
    phonetic: '/lets muːv ɒn/',
    role: 'linker',
    examples: [
      { en: "Let's move on to the next item on the agenda.", vi: 'Chúng ta chuyển tiếp sang mục tiếp theo trong chương trình nhé.' },
    ],
  },
  {
    id: 'it-meet-b1-04',
    domain: 'it',
    context: 'meeting',
    level: 'B1',
    english: 'keep it simple',
    vietnamese: 'giữ cho đơn giản',
    phonetic: '/kiːp ɪt ˈsɪmpəl/',
    role: 'closer',
    examples: [
      { en: 'For the first version, keep it simple and ship it.', vi: 'Cho phiên bản đầu, giữ cho đơn giản và phát hành đi.' },
    ],
  },
  {
    id: 'it-meet-b1-05',
    domain: 'it',
    context: 'meeting',
    level: 'B1',
    english: 'to sum up',
    vietnamese: 'tóm lại',
    phonetic: '/tə sʌm ʌp/',
    role: 'closer',
    examples: [
      { en: 'To sum up, we agreed on a two-week timeline.', vi: 'Tóm lại, chúng ta đã thống nhất timeline hai tuần.' },
    ],
  },
  {
    id: 'it-meet-b2-01',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: 'take into consideration',
    vietnamese: 'cân nhắc, xem xét',
    phonetic: '/teɪk ˈɪntə kənˌsɪdəˈreɪʃən/',
    role: 'linker',
    examples: [
      { en: 'We need to take into consideration the system load during peak hours.', vi: 'Chúng ta cần cân nhắc tải hệ thống trong giờ cao điểm.' },
    ],
  },
  {
    id: 'it-meet-b2-02',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: 'bear in mind',
    vietnamese: 'ghi nhớ, lưu ý',
    phonetic: '/beər ɪn maɪnd/',
    role: 'linker',
    examples: [
      { en: 'Bear in mind that the migration window is only two hours.', vi: 'Lưu ý rằng cửa sổ migration chỉ có hai tiếng.' },
    ],
  },
  {
    id: 'it-meet-b2-03',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: "I'd like to point out",
    vietnamese: 'tôi muốn chỉ ra',
    phonetic: '/aɪd laɪk tə pɔɪnt aʊt/',
    role: 'opener',
    examples: [
      { en: "I'd like to point out that the latency has improved by 30%.", vi: 'Tôi muốn chỉ ra rằng độ trễ đã cải thiện 30%.' },
    ],
  },
  {
    id: 'it-meet-b2-04',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: 'from a technical standpoint',
    vietnamese: 'từ góc độ kỹ thuật',
    phonetic: '/frɒm ə ˈteknɪkəl ˈstændpɔɪnt/',
    role: 'opener',
    examples: [
      { en: 'From a technical standpoint, the new schema is more robust.', vi: 'Từ góc độ kỹ thuật, schema mới vững hơn.' },
    ],
  },
  {
    id: 'it-meet-b2-05',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: 'to be on the same page',
    vietnamese: 'thống nhất quan điểm',
    phonetic: '/tə bi ɒn ðə seɪm peɪdʒ/',
    role: 'closer',
    examples: [
      { en: 'Before we close, let us make sure we are on the same page.', vi: 'Trước khi kết thúc, hãy chắc rằng chúng ta đã thống nhất quan điểm.' },
    ],
  },

  // ===== 8.2 IT — email =====
  {
    id: 'it-email-b1-01',
    domain: 'it',
    context: 'email',
    level: 'B1',
    english: 'please find attached',
    vietnamese: 'vui lòng xem file đính kèm',
    phonetic: '/pliːz faɪnd əˈtætʃt/',
    role: 'opener',
    examples: [
      { en: 'Please find attached the latest build of the app.', vi: 'Vui lòng xem file đính kèm — bản build mới nhất của app.' },
    ],
  },
  {
    id: 'it-email-b1-02',
    domain: 'it',
    context: 'email',
    level: 'B1',
    english: 'in the meantime',
    vietnamese: 'trong lúc chờ đợi',
    phonetic: '/ɪn ðə ˈmiːntaɪm/',
    role: 'linker',
    examples: [
      { en: 'In the meantime, please continue testing the staging build.', vi: 'Trong lúc chờ đợi, hãy tiếp tục test bản staging nhé.' },
    ],
  },
  {
    id: 'it-email-b1-03',
    domain: 'it',
    context: 'email',
    level: 'B1',
    english: 'get back to me',
    vietnamese: 'phản hồi lại tôi',
    phonetic: '/ɡet bæk tə miː/',
    role: 'closer',
    examples: [
      { en: 'Please get back to me by end of day.', vi: 'Vui lòng phản hồi lại tôi trước cuối ngày.' },
    ],
  },
  {
    id: 'it-email-b1-04',
    domain: 'it',
    context: 'email',
    level: 'B1',
    english: 'thanks in advance',
    vietnamese: 'cảm ơn trước',
    phonetic: '/θæŋks ɪn ədˈvɑːns/',
    role: 'closer',
    examples: [
      { en: 'Thanks in advance for the quick review.', vi: 'Cảm ơn trước vì review nhanh nhé.' },
    ],
  },
  {
    id: 'it-email-b2-01',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: 'for your reference',
    vietnamese: 'để bạn tham khảo',
    phonetic: '/fə jɔː ˈrefərəns/',
    role: 'opener',
    examples: [
      { en: 'For your reference, here is the updated architecture diagram.', vi: 'Để bạn tham khảo, đây là sơ đồ kiến trúc cập nhật.' },
    ],
  },
  {
    id: 'it-email-b2-02',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: 'with regard to',
    vietnamese: 'liên quan đến',
    phonetic: '/wɪð rɪˈɡɑːd tə/',
    role: 'opener',
    examples: [
      { en: 'With regard to the deployment schedule, we are on track.', vi: 'Liên quan đến lịch deploy, chúng ta đang đúng tiến độ.' },
    ],
  },
  {
    id: 'it-email-b2-03',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: "I'll keep you posted",
    vietnamese: 'tôi sẽ cập nhật cho bạn',
    phonetic: '/aɪl kiːp juː ˈpəʊstɪd/',
    role: 'closer',
    examples: [
      { en: "I'll keep you posted on any blockers.", vi: 'Tôi sẽ cập nhật cho bạn nếu có vướng mắc.' },
    ],
  },
  {
    id: 'it-email-b2-04',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: 'feel free to reach out',
    vietnamese: 'cứ thoải mái liên hệ',
    phonetic: '/fiːl friː tə riːtʃ aʊt/',
    role: 'closer',
    examples: [
      { en: 'Feel free to reach out if anything is unclear.', vi: 'Cứ thoải mái liên hệ nếu có gì chưa rõ.' },
    ],
  },

  // ===== 8.3 IT — incident =====
  {
    id: 'it-inc-b2-01',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: "it's down",
    vietnamese: 'nó đang ngừng hoạt động',
    phonetic: '/ɪts daʊn/',
    role: 'opener',
    examples: [
      { en: "It's down — the API has been returning 500s for the last ten minutes.", vi: 'Nó đang ngừng hoạt động — API trả về 500 suốt mười phút qua.' },
    ],
  },
  {
    id: 'it-inc-b2-02',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: 'root cause analysis',
    vietnamese: 'phân tích nguyên nhân gốc',
    phonetic: '/ruːt kɔːz əˈnæləsɪs/',
    role: 'filler',
    examples: [
      { en: 'We are running a root cause analysis on the failed deploy.', vi: 'Chúng tôi đang phân tích nguyên nhân gốc của lần deploy lỗi.' },
    ],
  },
  {
    id: 'it-inc-b2-03',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: 'to isolate the issue',
    vietnamese: 'cô lập vấn đề',
    phonetic: '/tə ˈaɪsəleɪt ði ˈɪʃuː/',
    role: 'linker',
    examples: [
      { en: 'First, we need to isolate the issue to a single shard.', vi: 'Đầu tiên, ta cần cô lập vấn đề về một shard.' },
    ],
  },
  {
    id: 'it-inc-b2-04',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: 'to bring it back up',
    vietnamese: 'khôi phục lại',
    phonetic: '/tə brɪŋ ɪt bæk ʌp/',
    role: 'closer',
    examples: [
      { en: 'Once the patch is in, we will bring it back up.', vi: 'Khi patch vào rồi, chúng tôi sẽ khôi phục lại.' },
    ],
  },
  {
    id: 'it-inc-b2-05',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: 'within the expected timeframe',
    vietnamese: 'trong khung thời gian dự kiến',
    phonetic: '/wɪˈðɪn ði ɪkˈspektɪd ˈtaɪmfreɪm/',
    role: 'closer',
    examples: [
      { en: 'We expect full recovery within the expected timeframe.', vi: 'Chúng tôi kỳ vọng phục hồi đầy đủ trong khung thời gian dự kiến.' },
    ],
  },

  // ===== 8.4 Business — meeting =====
  {
    id: 'biz-meet-b1-01',
    domain: 'business',
    context: 'meeting',
    level: 'B1',
    english: 'to kick things off',
    vietnamese: 'bắt đầu buổi họp',
    phonetic: '/tə kɪk θɪŋz ɒf/',
    role: 'opener',
    examples: [
      { en: 'To kick things off, let us review last quarter numbers.', vi: 'Bắt đầu buổi họp, ta cùng xem lại số liệu quý trước nhé.' },
    ],
  },
  {
    id: 'biz-meet-b1-02',
    domain: 'business',
    context: 'meeting',
    level: 'B1',
    english: 'on the agenda',
    vietnamese: 'trong chương trình nghị sự',
    phonetic: '/ɒn ði əˈdʒendə/',
    role: 'filler',
    examples: [
      { en: 'Hiring is the second item on the agenda today.', vi: 'Tuyển dụng là mục thứ hai trong chương trình nghị sự hôm nay.' },
    ],
  },
  {
    id: 'biz-meet-b1-03',
    domain: 'business',
    context: 'meeting',
    level: 'B1',
    english: 'to go through',
    vietnamese: 'xem qua, đi qua',
    phonetic: '/tə ɡəʊ θruː/',
    role: 'linker',
    examples: [
      { en: 'Let us go through the proposal one more time.', vi: 'Chúng ta cùng đi qua bản đề xuất thêm một lần nữa.' },
    ],
  },
  {
    id: 'biz-meet-b1-04',
    domain: 'business',
    context: 'meeting',
    level: 'B1',
    english: 'at the end of the day',
    vietnamese: 'cuối cùng thì',
    phonetic: '/æt ði end əv ðə deɪ/',
    role: 'closer',
    examples: [
      { en: 'At the end of the day, we need to ship the product.', vi: 'Cuối cùng thì, chúng ta cần phải ra mắt sản phẩm.' },
    ],
  },
  {
    id: 'biz-meet-b2-01',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'from a business perspective',
    vietnamese: 'từ góc độ kinh doanh',
    phonetic: '/frɒm ə ˈbɪznəs pəˈspektɪv/',
    role: 'opener',
    examples: [
      { en: 'From a business perspective, this market is still growing.', vi: 'Từ góc độ kinh doanh, thị trường này vẫn đang tăng trưởng.' },
    ],
  },
  {
    id: 'biz-meet-b2-02',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'to align on',
    vietnamese: 'thống nhất về',
    phonetic: '/tə əˈlaɪn ɒn/',
    role: 'linker',
    examples: [
      { en: 'We need to align on the launch date before we move on.', vi: 'Chúng ta cần thống nhất về ngày ra mắt trước khi tiếp tục.' },
    ],
  },
  {
    id: 'biz-meet-b2-03',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'moving forward',
    vietnamese: 'tiến tới, về phía trước',
    phonetic: '/ˈmuːvɪŋ ˈfɔːwəd/',
    role: 'linker',
    examples: [
      { en: 'Moving forward, we will run weekly syncs with the team.', vi: 'Tiến tới, ta sẽ chạy sync hàng tuần với team.' },
    ],
  },
  {
    id: 'biz-meet-b2-04',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'to put it on hold',
    vietnamese: 'tạm gác lại',
    phonetic: '/tə pʊt ɪt ɒn həʊld/',
    role: 'closer',
    examples: [
      { en: 'Given the budget, let us put it on hold for now.', vi: 'Với ngân sách hiện tại, ta tạm gác lại nhé.' },
    ],
  },

  // ===== 8.5 Business — email =====
  {
    id: 'biz-email-b1-01',
    domain: 'business',
    context: 'email',
    level: 'B1',
    english: 'I hope this finds you well',
    vietnamese: 'hy vọng bạn vẫn khỏe',
    phonetic: '/aɪ həʊp ðɪs faɪndz juː wel/',
    role: 'opener',
    examples: [
      { en: 'Hi Mai, I hope this finds you well.', vi: 'Chào Mai, hy vọng bạn vẫn khỏe.' },
    ],
  },
  {
    id: 'biz-email-b1-02',
    domain: 'business',
    context: 'email',
    level: 'B1',
    english: 'just a quick follow-up',
    vietnamese: 'chỉ là một lần nhắc lại ngắn',
    phonetic: '/dʒʌst ə kwɪk ˈfɒləʊ ʌp/',
    role: 'opener',
    examples: [
      { en: 'Just a quick follow-up on the contract we discussed last week.', vi: 'Chỉ là một lần nhắc lại ngắn về hợp đồng ta bàn tuần trước.' },
    ],
  },
  {
    id: 'biz-email-b1-03',
    domain: 'business',
    context: 'email',
    level: 'B1',
    english: 'at your earliest convenience',
    vietnamese: 'khi nào bạn tiện',
    phonetic: '/æt jɔː ˈɜːliɪst kənˈviːniəns/',
    role: 'closer',
    examples: [
      { en: 'Please reply at your earliest convenience.', vi: 'Vui lòng phản hồi khi nào bạn tiện nhé.' },
    ],
  },
  {
    id: 'biz-email-b1-04',
    domain: 'business',
    context: 'email',
    level: 'B1',
    english: 'looking forward to',
    vietnamese: 'rất mong',
    phonetic: '/ˈlʊkɪŋ ˈfɔːwəd tə/',
    role: 'closer',
    examples: [
      { en: 'Looking forward to your feedback on the draft.', vi: 'Rất mong nhận phản hồi của bạn về bản nháp.' },
    ],
  },
  {
    id: 'biz-email-b2-01',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'to touch base',
    vietnamese: 'trao đổi nhanh',
    phonetic: '/tə tʌtʃ beɪs/',
    role: 'opener',
    examples: [
      { en: 'Wanted to touch base on the proposal before Friday.', vi: 'Muốn trao đổi nhanh về đề xuất trước thứ Sáu.' },
    ],
  },
  {
    id: 'biz-email-b2-02',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'as per our conversation',
    vietnamese: 'theo đúng như cuộc trao đổi',
    phonetic: '/æz pɜː aʊə ˌkɒnvəˈseɪʃən/',
    role: 'opener',
    examples: [
      { en: 'As per our conversation, here are the next steps.', vi: 'Theo đúng như cuộc trao đổi, đây là các bước tiếp theo.' },
    ],
  },
  {
    id: 'biz-email-b2-03',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'should you have any questions',
    vietnamese: 'nếu bạn có bất kỳ câu hỏi nào',
    phonetic: '/ʃʊd juː hæv ˈeni ˈkwestʃənz/',
    role: 'closer',
    examples: [
      { en: 'Should you have any questions, do not hesitate to reach out.', vi: 'Nếu bạn có bất kỳ câu hỏi nào, cứ thoải mái liên hệ nhé.' },
    ],
  },
  {
    id: 'biz-email-b2-04',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'I look forward to your reply',
    vietnamese: 'tôi mong nhận được hồi âm',
    phonetic: '/aɪ lʊk ˈfɔːwəd tə jɔː rɪˈplaɪ/',
    role: 'closer',
    examples: [
      { en: 'I look forward to your reply by Wednesday.', vi: 'Tôi mong nhận được hồi âm của bạn trước thứ Tư.' },
    ],
  },

  // ===== 8.6 Business — negotiation =====
  {
    id: 'biz-neg-b2-01',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'our bottom line is',
    vietnamese: 'giới hạn cuối cùng của chúng tôi là',
    phonetic: '/aʊə ˈbɒtəm laɪn ɪz/',
    role: 'opener',
    examples: [
      { en: 'Our bottom line is 20% margin on this contract.', vi: 'Giới hạn cuối của chúng tôi là biên 20% trên hợp đồng này.' },
    ],
  },
  {
    id: 'biz-neg-b2-02',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'on a tight budget',
    vietnamese: 'với ngân sách eo hẹp',
    phonetic: '/ɒn ə taɪt ˈbʌdʒɪt/',
    role: 'filler',
    examples: [
      { en: 'We are on a tight budget this quarter.', vi: 'Chúng tôi đang với ngân sách eo hẹp trong quý này.' },
    ],
  },
  {
    id: 'biz-neg-b2-03',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'to meet us halfway',
    vietnamese: 'nhân nhượng nửa chừng',
    phonetic: '/tə miːt ʌs hɑːfˈweɪ/',
    role: 'linker',
    examples: [
      { en: 'If you can meet us halfway on the timeline, we can close.', vi: 'Nếu bạn nhân nhượng nửa chừng về timeline, ta có thể chốt.' },
    ],
  },
  {
    id: 'biz-neg-b2-04',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'to sweeten the deal',
    vietnamese: 'làm cho thương vụ hấp dẫn hơn',
    phonetic: '/tə ˈswiːtən ðə diːl/',
    role: 'closer',
    examples: [
      { en: 'Adding a free year of support will sweeten the deal.', vi: 'Thêm một năm hỗ trợ miễn phí sẽ làm cho thương vụ hấp dẫn hơn.' },
    ],
  },
  {
    id: 'biz-neg-b2-05',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'to come to an agreement',
    vietnamese: 'đi đến thỏa thuận',
    phonetic: '/tə kʌm tə ən əˈɡriːmənt/',
    role: 'closer',
    examples: [
      { en: 'I think we are ready to come to an agreement.', vi: 'Tôi nghĩ chúng ta đã sẵn sàng đi đến thỏa thuận.' },
    ],
  },

  // ===== 8.7 Daily — small-talk =====
  {
    id: 'day-st-b1-01',
    domain: 'daily',
    context: 'small-talk',
    level: 'B1',
    english: "how's it going",
    vietnamese: 'dạo này thế nào',
    phonetic: '/haʊz ɪt ˈɡəʊɪŋ/',
    role: 'opener',
    examples: [
      { en: "Hey, how's it going? Long time no see.", vi: 'Ê, dạo này thế nào? Lâu rồi không gặp.' },
    ],
  },
  {
    id: 'day-st-b1-02',
    domain: 'daily',
    context: 'small-talk',
    level: 'B1',
    english: 'long time no see',
    vietnamese: 'lâu rồi không gặp',
    phonetic: '/lɒŋ taɪm nəʊ siː/',
    role: 'opener',
    examples: [
      { en: 'Long time no see — how have you been?', vi: 'Lâu rồi không gặp — dạo này bạn thế nào?' },
    ],
  },
  {
    id: 'day-st-b1-03',
    domain: 'daily',
    context: 'small-talk',
    level: 'B1',
    english: 'by the way',
    vietnamese: 'nhân tiện',
    phonetic: '/baɪ ðə weɪ/',
    role: 'linker',
    examples: [
      { en: 'By the way, did you finish the book I lent you?', vi: 'Nhân tiện, bạn đọc xong cuốn sách tôi cho mượn chưa?' },
    ],
  },
  {
    id: 'day-st-b1-04',
    domain: 'daily',
    context: 'small-talk',
    level: 'B1',
    english: 'to catch up',
    vietnamese: 'hàn huyên, cập nhật chuyện',
    phonetic: '/tə kætʃ ʌp/',
    role: 'closer',
    examples: [
      { en: 'We should catch up over coffee this weekend.', vi: 'Cuối tuần này mình hàn huyên qua cà phê nhé.' },
    ],
  },
  {
    id: 'day-st-b2-01',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: "it's been a while",
    vietnamese: 'đã một thời gian rồi',
    phonetic: '/ɪts biːn ə waɪl/',
    role: 'opener',
    examples: [
      { en: "It's been a while since we last met.", vi: 'Đã một thời gian rồi kể từ lần gặp cuối.' },
    ],
  },
  {
    id: 'day-st-b2-02',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: 'speaking of which',
    vietnamese: 'nói đến chuyện đó',
    phonetic: '/ˈspiːkɪŋ əv wɪtʃ/',
    role: 'linker',
    examples: [
      { en: 'Speaking of which, have you heard the news?', vi: 'Nói đến chuyện đó, bạn đã nghe tin chưa?' },
    ],
  },
  {
    id: 'day-st-b2-03',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: 'to keep things short',
    vietnamese: 'giữ cho ngắn gọn',
    phonetic: '/tə kiːp θɪŋz ʃɔːt/',
    role: 'opener',
    examples: [
      { en: 'To keep things short, I will just send you a summary.', vi: 'Giữ cho ngắn gọn, tôi sẽ gửi bạn tóm tắt thôi.' },
    ],
  },
  {
    id: 'day-st-b2-04',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: "let's pick this up later",
    vietnamese: 'để dành nói tiếp sau',
    phonetic: '/lets pɪk ðɪs ʌp ˈleɪtə/',
    role: 'closer',
    examples: [
      { en: "Let's pick this up later — I have a call in five.", vi: 'Để dành nói tiếp sau nhé — tôi có cuộc gọi trong năm phút nữa.' },
    ],
  },

  // ===== 8.8 Daily — opinion =====
  {
    id: 'day-op-b1-01',
    domain: 'daily',
    context: 'opinion',
    level: 'B1',
    english: 'as far as I know',
    vietnamese: 'theo như tôi biết',
    phonetic: '/æz fɑːr æz aɪ nəʊ/',
    role: 'opener',
    examples: [
      { en: 'As far as I know, the meeting has been moved to Thursday.', vi: 'Theo như tôi biết, cuộc họp đã được chuyển sang thứ Năm.' },
    ],
  },
  {
    id: 'day-op-b1-02',
    domain: 'daily',
    context: 'opinion',
    level: 'B1',
    english: 'to be honest',
    vietnamese: 'thành thật mà nói',
    phonetic: '/tə bi ˈɒnɪst/',
    role: 'opener',
    examples: [
      { en: 'To be honest, I do not think the plan is realistic.', vi: 'Thành thật mà nói, tôi không nghĩ kế hoạch này khả thi.' },
    ],
  },
  {
    id: 'day-op-b1-03',
    domain: 'daily',
    context: 'opinion',
    level: 'B1',
    english: 'in that case',
    vietnamese: 'trong trường hợp đó',
    phonetic: '/ɪn ðæt keɪs/',
    role: 'linker',
    examples: [
      { en: 'In that case, let us reschedule for next week.', vi: 'Trong trường hợp đó, ta dời lịch sang tuần sau nhé.' },
    ],
  },
  {
    id: 'day-op-b1-04',
    domain: 'daily',
    context: 'opinion',
    level: 'B1',
    english: 'it depends on',
    vietnamese: 'nó phụ thuộc vào',
    phonetic: '/ɪt dɪˈpendz ɒn/',
    role: 'filler',
    examples: [
      { en: 'It depends on the weather and the team size.', vi: 'Nó phụ thuộc vào thời tiết và quy mô team.' },
    ],
  },
  {
    id: 'day-op-b2-01',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: 'from my point of view',
    vietnamese: 'theo quan điểm của tôi',
    phonetic: '/frɒm maɪ pɔɪnt əv vjuː/',
    role: 'opener',
    examples: [
      { en: 'From my point of view, the risk is acceptable.', vi: 'Theo quan điểm của tôi, rủi ro là chấp nhận được.' },
    ],
  },
  {
    id: 'day-op-b2-02',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: 'that said',
    vietnamese: 'dù vậy',
    phonetic: '/ðæt sed/',
    role: 'linker',
    examples: [
      { en: 'That said, I would still recommend a smaller pilot first.', vi: 'Dù vậy, tôi vẫn đề xuất chạy pilot nhỏ trước.' },
    ],
  },
  {
    id: 'day-op-b2-03',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: 'to weigh the pros and cons',
    vietnamese: 'cân nhắc ưu nhược điểm',
    phonetic: '/tə weɪ ðə prəʊz ənd kɒnz/',
    role: 'linker',
    examples: [
      { en: 'Let us weigh the pros and cons before deciding.', vi: 'Chúng ta hãy cân nhắc ưu nhược điểm trước khi quyết.' },
    ],
  },
  {
    id: 'day-op-b2-04',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: "I couldn't agree more",
    vietnamese: 'tôi hoàn toàn đồng ý',
    phonetic: '/aɪ ˈkʊdnt əˈɡriː mɔː/',
    role: 'closer',
    examples: [
      { en: 'I could not agree more with your assessment.', vi: 'Tôi hoàn toàn đồng ý với đánh giá của bạn.' },
    ],
  },

  // ===== 8.9 Daily — daily-work =====
  {
    id: 'day-work-b1-01',
    domain: 'daily',
    context: 'daily-work',
    level: 'B1',
    english: 'first thing in the morning',
    vietnamese: 'việc đầu tiên buổi sáng',
    phonetic: '/fɜːst θɪŋ ɪn ðə ˈmɔːnɪŋ/',
    role: 'opener',
    examples: [
      { en: 'First thing in the morning, I review my emails.', vi: 'Việc đầu tiên buổi sáng, tôi xem lại email.' },
    ],
  },
  {
    id: 'day-work-b1-02',
    domain: 'daily',
    context: 'daily-work',
    level: 'B1',
    english: 'to run errands',
    vietnamese: 'chạy việc vặt',
    phonetic: '/tə rʌn ˈerəndz/',
    role: 'filler',
    examples: [
      { en: 'I will run errands during my lunch break.', vi: 'Tôi sẽ chạy việc vặt trong giờ nghỉ trưa.' },
    ],
  },
  {
    id: 'day-work-b1-03',
    domain: 'daily',
    context: 'daily-work',
    level: 'B1',
    english: 'to call it a day',
    vietnamese: 'kết thúc ngày làm việc',
    phonetic: '/tə kɔːl ɪt ə deɪ/',
    role: 'closer',
    examples: [
      { en: 'It is already 6pm — let us call it a day.', vi: 'Đã 6 giờ rồi — ta kết thúc ngày làm việc thôi.' },
    ],
  },
  {
    id: 'day-work-b1-04',
    domain: 'daily',
    context: 'daily-work',
    level: 'B1',
    english: 'to wrap things up',
    vietnamese: 'chốt lại mọi việc',
    phonetic: '/tə ræp θɪŋz ʌp/',
    role: 'closer',
    examples: [
      { en: 'Let us wrap things up before the standup.', vi: 'Ta chốt lại mọi việc trước giờ standup nhé.' },
    ],
  },
  {
    id: 'day-work-b2-01',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: 'to stay on top of',
    vietnamese: 'luôn nắm bắt, theo sát',
    phonetic: '/tə steɪ ɒn tɒp əv/',
    // Reclassified: linker -> opener (per spec's own tpl-day-work-01 example sentence).
    role: 'opener',
    examples: [
      { en: 'To stay on top of things, I check the dashboard every morning.', vi: 'Để luôn nắm bắt công việc, tôi xem dashboard mỗi sáng.' },
    ],
  },
  {
    id: 'day-work-b2-02',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: 'to push things forward',
    vietnamese: 'thúc đẩy công việc tiến lên',
    phonetic: '/tə pʊʃ θɪŋz ˈfɔːwəd/',
    role: 'linker',
    examples: [
      { en: 'We need to push things forward before the freeze.', vi: 'Chúng ta cần thúc đẩy công việc tiến lên trước đợt freeze.' },
    ],
  },
  {
    id: 'day-work-b2-03',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: 'to prioritize the tasks',
    vietnamese: 'ưu tiên các việc',
    phonetic: '/tə praɪˈɒrɪtaɪz ðə tɑːsks/',
    // Reclassified: filler -> linker (per spec's own tpl-day-work-01 example sentence).
    role: 'linker',
    examples: [
      { en: 'Let us prioritize the tasks before the sprint planning.', vi: 'Chúng ta hãy ưu tiên các việc trước buổi sprint planning.' },
    ],
  },
  {
    id: 'day-work-b2-04',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: 'to get it done by',
    vietnamese: 'hoàn thành trước',
    phonetic: '/tə ɡet ɪt dʌn baɪ/',
    role: 'closer',
    examples: [
      { en: 'We need to get it done by Friday.', vi: 'Chúng ta cần hoàn thành trước thứ Sáu.' },
    ],
  },
];

export const SEED_TEMPLATES: PhraseTemplate[] = [
  // ===== 8.10.1 IT — meeting (B2) =====
  {
    id: 'tpl-it-meet-01',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: 'It would be better if we could take into consideration the system load before we proceed.',
    vietnamese: 'Sẽ tốt hơn nếu chúng ta cân nhắc tải hệ thống trước khi tiếp tục.',
    structure: 'It would be better if {subject} {modal} {chunk:linker} the {noun} before we {verb}.',
    slots: [
      { name: 'subject', role: null, options: ['we', 'you', 'the team'] },
      { name: 'modal', role: null, options: ['could', 'would'] },
      { name: 'linker', role: 'linker' },
      { name: 'noun', role: null, options: ['system load', 'performance', 'the requirements'] },
      { name: 'verb', role: null, options: ['move on', 'proceed'] },
    ],
    example: {
      en: 'It would be better if we could take into consideration the system load before we proceed.',
      vi: 'Sẽ tốt hơn nếu chúng ta cân nhắc tải hệ thống trước khi tiếp tục.',
    },
  },
  {
    id: 'tpl-it-meet-02',
    domain: 'it',
    context: 'meeting',
    level: 'B2',
    english: "I'd like to point out that we should bear in mind the system load before we proceed.",
    vietnamese: 'Tôi muốn chỉ ra rằng chúng ta nên ghi nhớ tải hệ thống trước khi tiếp tục.',
    structure: '{chunk:opener} that {chunk:linker} the {noun} before we {verb}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'linker', role: 'linker' },
      { name: 'noun', role: null, options: ['the requirements', 'the deadline', 'the system load'] },
      { name: 'verb', role: null, options: ['proceed', 'make a decision'] },
    ],
    example: {
      en: "I'd like to point out that we should bear in mind the system load before we proceed.",
      vi: 'Tôi muốn chỉ ra rằng chúng ta nên ghi nhớ tải hệ thống trước khi tiếp tục.',
    },
  },

  // ===== 8.10.2 IT — email (B2) =====
  {
    id: 'tpl-it-email-01',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: "For your reference, here is the report — I'll keep you posted on any updates.",
    vietnamese: 'Để bạn tham khảo, đây là báo cáo — tôi sẽ cập nhật cho bạn nếu có thay đổi.',
    structure: '{chunk:opener} {noun} — {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'noun', role: null, options: ['here is the report', 'the updated docs', 'the meeting notes'] },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: "For your reference, here is the report — I'll keep you posted on any updates.",
      vi: 'Để bạn tham khảo, đây là báo cáo — tôi sẽ cập nhật cho bạn nếu có thay đổi.',
    },
  },
  {
    id: 'tpl-it-email-02',
    domain: 'it',
    context: 'email',
    level: 'B2',
    english: 'With regard to the incident — feel free to reach out if you have questions.',
    vietnamese: 'Liên quan đến sự cố — cứ thoải mái liên hệ nếu bạn có thắc mắc.',
    structure: '{chunk:opener} the {noun} — {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'noun', role: null, options: ['incident', 'deployment', 'migration'] },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'With regard to the incident — feel free to reach out if you have questions.',
      vi: 'Liên quan đến sự cố — cứ thoải mái liên hệ nếu bạn có thắc mắc.',
    },
  },

  // ===== 8.10.3 IT — incident (B2) =====
  {
    id: 'tpl-it-inc-01',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: "It's down — we're doing root cause analysis to bring it back up within the expected timeframe.",
    vietnamese: 'Hệ thống đang ngừng hoạt động — chúng tôi đang phân tích nguyên nhân gốc để khôi phục trong khung thời gian dự kiến.',
    structure: "{chunk:opener} — we're doing {chunk:filler} to {chunk:closer} within {timeframe}.",
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'filler', role: 'filler' },
      { name: 'closer', role: 'closer' },
      { name: 'timeframe', role: null, options: ['the hour', 'the expected timeframe', '2 hours'] },
    ],
    example: {
      en: "It's down — we're doing root cause analysis to bring it back up within the expected timeframe.",
      vi: 'Hệ thống đang ngừng hoạt động — chúng tôi đang phân tích nguyên nhân gốc để khôi phục trong khung thời gian dự kiến.',
    },
  },
  {
    id: 'tpl-it-inc-02',
    domain: 'it',
    context: 'incident',
    level: 'B2',
    english: 'We need to isolate the issue first, then bring it back up.',
    vietnamese: 'Chúng ta cần cô lập vấn đề trước, sau đó khôi phục.',
    structure: 'We need to {chunk:linker} first, then {chunk:closer}.',
    slots: [
      { name: 'linker', role: 'linker' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'We need to isolate the issue first, then bring it back up.',
      vi: 'Chúng ta cần cô lập vấn đề trước, sau đó khôi phục.',
    },
  },

  // ===== 8.10.4 Business — meeting (B2) =====
  {
    id: 'tpl-biz-meet-01',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'From a business perspective, we should align on this before we put it on hold.',
    vietnamese: 'Từ góc độ kinh doanh, chúng ta nên thống nhất về việc này trước khi tạm gác lại.',
    structure: '{chunk:opener}, {subject} should {verb} on this before we {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'subject', role: null, options: ['we', 'the team', 'management'] },
      { name: 'verb', role: null, options: ['align', 'decide', 'discuss'] },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'From a business perspective, we should align on this before we put it on hold.',
      vi: 'Từ góc độ kinh doanh, chúng ta nên thống nhất về việc này trước khi tạm gác lại.',
    },
  },
  {
    id: 'tpl-biz-meet-02',
    domain: 'business',
    context: 'meeting',
    level: 'B2',
    english: 'Moving forward, let\'s go through the agenda.',
    vietnamese: 'Tiến tới, chúng ta hãy đi qua chương trình nghị sự.',
    structure: "{chunk:linker}, let's {verb} {noun}.",
    slots: [
      { name: 'linker', role: 'linker' },
      { name: 'verb', role: null, options: ['go through', 'review', 'discuss'] },
      { name: 'noun', role: null, options: ['the agenda', 'the budget', 'the timeline'] },
    ],
    example: {
      en: "Moving forward, let's go through the agenda.",
      vi: 'Tiến tới, chúng ta hãy đi qua chương trình nghị sự.',
    },
  },

  // ===== 8.10.5 Business — email (B2) =====
  {
    id: 'tpl-biz-email-01',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'As per our conversation, I look forward to your reply.',
    vietnamese: 'Theo đúng như cuộc trao đổi, tôi mong nhận được hồi âm.',
    structure: '{chunk:opener} — {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'As per our conversation, I look forward to your reply.',
      vi: 'Theo đúng như cuộc trao đổi, tôi mong nhận được hồi âm.',
    },
  },
  {
    id: 'tpl-biz-email-02',
    domain: 'business',
    context: 'email',
    level: 'B2',
    english: 'To touch base on the proposal — let me know at your earliest convenience.',
    vietnamese: 'Để trao đổi nhanh về đề xuất — cho tôi biết khi nào bạn tiện.',
    structure: '{chunk:opener} the {noun} {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'noun', role: null, options: ['the proposal', 'the contract', 'the timeline'] },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'To touch base on the proposal — let me know at your earliest convenience.',
      vi: 'Để trao đổi nhanh về đề xuất — cho tôi biết khi nào bạn tiện.',
    },
  },

  // ===== 8.10.6 Business — negotiation (B2) =====
  {
    id: 'tpl-biz-neg-01',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'Our bottom line is 20% — can you meet us halfway on the price?',
    vietnamese: 'Giới hạn cuối của chúng tôi là 20% — bạn có thể nhân nhượng nửa chừng về giá không?',
    structure: '{chunk:opener} {number} — can you {chunk:linker} on the {noun}?',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'number', role: null, options: ['20%', '15%', '10%'] },
      { name: 'linker', role: 'linker' },
      { name: 'noun', role: null, options: ['price', 'timeline', 'scope'] },
    ],
    example: {
      en: 'Our bottom line is 20% — can you meet us halfway on the price?',
      vi: 'Giới hạn cuối của chúng tôi là 20% — bạn có thể nhân nhượng nửa chừng về giá không?',
    },
  },
  {
    id: 'tpl-biz-neg-02',
    domain: 'business',
    context: 'negotiation',
    level: 'B2',
    english: 'If you can meet us halfway, we can come to an agreement.',
    vietnamese: 'Nếu bạn nhân nhượng nửa chừng, chúng ta có thể đi đến thỏa thuận.',
    structure: 'If you can {chunk:linker}, we can {chunk:closer}.',
    slots: [
      { name: 'linker', role: 'linker' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'If you can meet us halfway, we can come to an agreement.',
      vi: 'Nếu bạn nhân nhượng nửa chừng, chúng ta có thể đi đến thỏa thuận.',
    },
  },

  // ===== 8.10.7 Daily — small-talk (B2) =====
  {
    id: 'tpl-day-st-01',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: "It's been a while — speaking of which, we should catch up.",
    vietnamese: 'Đã một thời gian rồi — nhân tiện nói đến, chúng ta nên hàn huyên.',
    structure: '{chunk:opener} — {chunk:linker}, {subject} {verb}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'linker', role: 'linker' },
      { name: 'subject', role: null, options: ['we', 'you and I'] },
      { name: 'verb', role: null, options: ['catch up', 'meet up', 'have coffee'] },
    ],
    example: {
      en: "It's been a while — speaking of which, we should catch up.",
      vi: 'Đã một thời gian rồi — nhân tiện nói đến, chúng ta nên hàn huyên.',
    },
  },
  {
    id: 'tpl-day-st-02',
    domain: 'daily',
    context: 'small-talk',
    level: 'B2',
    english: 'To keep things short, let\'s pick this up later.',
    vietnamese: 'Để giữ cho ngắn gọn, để dành nói tiếp sau.',
    structure: "{chunk:opener}, {chunk:closer}.",
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: "To keep things short, let's pick this up later.",
      vi: 'Để giữ cho ngắn gọn, để dành nói tiếp sau.',
    },
  },

  // ===== 8.10.8 Daily — opinion (B2) =====
  {
    id: 'tpl-day-op-01',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: 'From my point of view, we should weigh the pros and cons.',
    vietnamese: 'Theo quan điểm của tôi, chúng ta nên cân nhắc ưu nhược điểm.',
    structure: '{chunk:opener}, {subject} {verb} {noun}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'subject', role: null, options: ['we', 'you', 'they'] },
      { name: 'verb', role: null, options: ['should weigh', 'need to consider', 'must discuss'] },
      { name: 'noun', role: null, options: ['the pros and cons', 'the options', 'the risks'] },
    ],
    example: {
      en: 'From my point of view, we should weigh the pros and cons.',
      vi: 'Theo quan điểm của tôi, chúng ta nên cân nhắc ưu nhược điểm.',
    },
  },
  {
    id: 'tpl-day-op-02',
    domain: 'daily',
    context: 'opinion',
    level: 'B2',
    english: 'To be honest, I couldn\'t agree more.',
    vietnamese: 'Thành thật mà nói, tôi hoàn toàn đồng ý.',
    structure: '{chunk:opener} — {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: "To be honest, I couldn't agree more.",
      vi: 'Thành thật mà nói, tôi hoàn toàn đồng ý.',
    },
  },

  // ===== 8.10.9 Daily — daily-work (B2) =====
  {
    id: 'tpl-day-work-01',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: 'To stay on top of things, we need to prioritize the tasks to get them done by Friday.',
    vietnamese: 'Để luôn theo sát công việc, chúng ta cần ưu tiên các việc để hoàn thành trước thứ Sáu.',
    structure: '{chunk:opener}, {subject} need to {chunk:linker} {noun} to {chunk:closer}.',
    slots: [
      { name: 'opener', role: 'opener' },
      { name: 'subject', role: null, options: ['we', 'I', 'the team'] },
      { name: 'linker', role: 'linker' },
      { name: 'noun', role: null, options: ['the tasks', 'the deadlines'] },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: 'To stay on top of things, we need to prioritize the tasks to get them done by Friday.',
      vi: 'Để luôn theo sát công việc, chúng ta cần ưu tiên các việc để hoàn thành trước thứ Sáu.',
    },
  },
  {
    id: 'tpl-day-work-02',
    domain: 'daily',
    context: 'daily-work',
    level: 'B2',
    english: "Let's push things forward and wrap things up.",
    vietnamese: 'Hãy thúc đẩy công việc và chốt lại mọi việc.',
    structure: "Let's {chunk:linker} and {chunk:closer}.",
    slots: [
      { name: 'linker', role: 'linker' },
      { name: 'closer', role: 'closer' },
    ],
    example: {
      en: "Let's push things forward and wrap things up.",
      vi: 'Hãy thúc đẩy công việc và chốt lại mọi việc.',
    },
  },
];
