import type { Scenario } from '../../src/app/sub-app/phrase-lab/models/scenario.model';

/**
 * SEED_SCENARIOS — đổ vào Firestore collection `phrase_scenarios` bằng
 * `npm run seed:scenarios` (xem seed-phrase-scenarios.ts).
 * Mọi chunk ID phải tồn tại trong SEED_CHUNKS.
 */
export const SEED_SCENARIOS: Scenario[] = [
  {
    id: 'scn-it-meet-a2-01',
    level: 'A2',
    context: 'meeting',
    title: 'Mở đầu cuộc họp',
    turns: [
      {
        speakerLine: 'Good morning everyone, I think we are ready to start.',
        speakerLineVi: 'Chào buổi sáng mọi người, tôi nghĩ chúng ta đã sẵn sàng bắt đầu.',
        answers: [{ ids: ['it-meet-a2-01'] }],
        replyLine: 'Great, thank you for kicking us off.',
        replyLineVi: 'Tuyệt, cảm ơn bạn đã mở đầu.',
      },
      {
        speakerLine: 'Before we move on, does anyone have any questions about the agenda?',
        speakerLineVi: 'Trước khi tiếp tục, có ai có câu hỏi gì về chương trình không?',
        answers: [{ ids: ['it-meet-a2-02'] }, { ids: ['it-meet-a2-03'] }],
        replyLine: 'Sure, go ahead.',
        replyLineVi: 'Chắc chắn rồi, bạn cứ nói.',
      },
      {
        speakerLine: 'Alright, I think we covered everything on the list.',
        speakerLineVi: 'Được rồi, tôi nghĩ chúng ta đã xong mọi thứ trong danh sách.',
        answers: [{ ids: ['it-meet-a2-04'] }],
        replyLine: 'Perfect, see you at the next one.',
        replyLineVi: 'Hoàn hảo, hẹn gặp ở buổi sau.',
      },
    ],
  },
  {
    id: 'scn-it-meet-b1-01',
    level: 'B1',
    context: 'meeting',
    title: 'Rà soát sprint',
    turns: [
      {
        speakerLine: "Let's start by reviewing where we are in the sprint.",
        speakerLineVi: 'Bắt đầu bằng việc xem xét chúng ta đang ở đâu trong sprint.',
        answers: [{ ids: ['it-meet-b1-31'] }],
        replyLine: 'Thanks, we will prepare the demo.',
        replyLineVi: 'Cảm ơn, chúng tôi sẽ chuẩn bị bản demo.',
      },
      {
        speakerLine: 'What should we look at next?',
        speakerLineVi: 'Tiếp theo chúng ta nên xem xét gì?',
        answers: [{ ids: ['it-meet-b1-33'] }],
        replyLine: 'Good point, let us hear the details.',
        replyLineVi: 'Ý hay, hãy nghe chi tiết.',
      },
      {
        speakerLine: 'Anything else to mention before we close?',
        speakerLineVi: 'Còn gì cần nhắc trước khi kết thúc không?',
        answers: [{ ids: ['it-meet-b1-34'] }, { ids: ['it-meet-b1-35'] }],
        replyLine: 'Okay, let us check again tomorrow.',
        replyLineVi: 'Được, hãy kiểm tra lại vào ngày mai.',
      },
      {
        speakerLine: "I think that's everything for today.",
        speakerLineVi: 'Tôi nghĩ hôm nay đến đây là hết.',
        answers: [{ ids: ['it-meet-b1-36'] }],
        replyLine: "Sure, I'll take the notes.",
        replyLineVi: 'Chắc chắn rồi, tôi sẽ ghi lại.',
      },
    ],
  },
  {
    id: 'scn-it-meet-a2-02',
    level: 'A2',
    context: 'meeting',
    title: 'Bắt đầu khi chưa đủ người',
    turns: [
      {
        speakerLine: 'A few people have not joined the call yet.',
        speakerLineVi: 'Một vài người chưa vào cuộc gọi.',
        answers: [{ ids: ['it-meet-a2-06'] }, { ids: ['it-meet-a2-05'] }],
        replyLine: 'Yes, we can give them one more minute.',
        replyLineVi: 'Vâng, chúng ta có thể chờ họ thêm một phút.',
      },
      {
        speakerLine: 'Okay, everyone is here now.',
        speakerLineVi: 'Được rồi, giờ mọi người đã đủ mặt.',
        answers: [{ ids: ['it-meet-a2-07'] }],
        replyLine: 'Perfect, go ahead.',
        replyLineVi: 'Hoàn hảo, bạn cứ tiếp tục.',
      },
      {
        speakerLine: 'We will start with the project update.',
        speakerLineVi: 'Chúng ta sẽ bắt đầu với phần cập nhật dự án.',
        answers: [{ ids: ['it-meet-a2-09'] }],
        replyLine: 'Sounds good, we are ready.',
        replyLineVi: 'Nghe ổn, chúng tôi sẵn sàng.',
      },
    ],
  },
  {
    id: 'scn-it-meet-b1-02',
    level: 'B1',
    context: 'meeting',
    title: 'Cập nhật tiến độ dự án',
    turns: [
      {
        speakerLine: 'Let us start with the updates from the previous meeting.',
        speakerLineVi: 'Hãy bắt đầu với phần cập nhật từ cuộc họp trước.',
        answers: [{ ids: ['it-meet-b1-30'] }],
        replyLine: 'Good, please go through them one by one.',
        replyLineVi: 'Tốt, hãy đi qua từng mục một.',
      },
      {
        speakerLine: 'Do you want to see the code changes now?',
        speakerLineVi: 'Bạn có muốn xem các thay đổi mã nguồn ngay bây giờ không?',
        answers: [{ ids: ['it-meet-b1-32'] }],
        replyLine: 'Sure, that will help us understand.',
        replyLineVi: 'Chắc chắn rồi, điều đó sẽ giúp chúng ta hiểu rõ hơn.',
      },
      {
        speakerLine: 'Who is responsible for the remaining work?',
        speakerLineVi: 'Ai chịu trách nhiệm phần việc còn lại?',
        answers: [{ ids: ['it-meet-b1-34'] }],
        replyLine: 'Okay, we will follow up on that.',
        replyLineVi: 'Được, chúng tôi sẽ theo dõi việc đó.',
      },
      {
        speakerLine: 'Should we send a summary to everyone?',
        speakerLineVi: 'Chúng ta có nên gửi tóm tắt cho mọi người không?',
        answers: [{ ids: ['it-meet-b1-37'] }, { ids: ['it-meet-b1-36'] }],
        replyLine: 'Yes, that would be great.',
        replyLineVi: 'Vâng, điều đó thật tuyệt.',
      },
    ],
  },
  {
    id: 'scn-it-meet-b2-01',
    level: 'B2',
    context: 'meeting',
    title: 'Giai đoạn cuối sprint',
    turns: [
      {
        speakerLine: 'We have only a few days left in this iteration.',
        speakerLineVi: 'Chúng ta chỉ còn vài ngày cho vòng lặp này.',
        answers: [{ ids: ['it-meet-b2-30'] }],
        replyLine: 'I agree, let us stay focused.',
        replyLineVi: 'Tôi đồng ý, hãy tập trung.',
      },
      {
        speakerLine: 'We still need to prepare the backlog for next sprint.',
        speakerLineVi: 'Chúng ta vẫn cần chuẩn bị backlog cho sprint tới.',
        answers: [{ ids: ['it-meet-b2-31'] }],
        replyLine: 'Good, put it on the calendar.',
        replyLineVi: 'Tốt, hãy đưa vào lịch.',
      },
      {
        speakerLine: 'How do we evaluate our performance this time?',
        speakerLineVi: 'Chúng ta đánh giá hiệu suất lần này thế nào?',
        answers: [{ ids: ['it-meet-b2-32'] }, { ids: ['it-meet-b2-33'] }],
        replyLine: 'That is a fair way to look at it.',
        replyLineVi: 'Đó là cách nhìn hợp lý.',
      },
    ],
  },
  {
    id: 'scn-it-meet-a2-03',
    level: 'A2',
    context: 'meeting',
    title: 'Đặt câu hỏi giữa họp',
    turns: [
      {
        speakerLine: 'Thank you all for joining the meeting today.',
        speakerLineVi: 'Cảm ơn tất cả các bạn đã tham gia cuộc họp hôm nay.',
        answers: [{ ids: ['it-meet-a2-08'] }],
        replyLine: 'You are welcome, happy to be here.',
        replyLineVi: 'Không có gì, rất vui được tham gia.',
      },
      {
        speakerLine: 'I do not understand the last point.',
        speakerLineVi: 'Tôi không hiểu điểm cuối cùng.',
        answers: [{ ids: ['it-meet-a2-02'] }],
        replyLine: 'Of course, let me explain again.',
        replyLineVi: 'Tất nhiên, để tôi giải thích lại.',
      },
      {
        speakerLine: 'We will talk about the new feature next.',
        speakerLineVi: 'Tiếp theo chúng ta sẽ nói về tính năng mới.',
        answers: [{ ids: ['it-meet-a2-09'] }],
        replyLine: 'Great, I have some ideas about it.',
        replyLineVi: 'Tuyệt, tôi có vài ý tưởng về nó.',
      },
      {
        speakerLine: 'I think we are done for today.',
        speakerLineVi: 'Tôi nghĩ hôm nay đến đây là xong.',
        answers: [{ ids: ['it-meet-a2-04'] }],
        replyLine: 'Thanks everyone, see you next time.',
        replyLineVi: 'Cảm ơn mọi người, hẹn gặp lần sau.',
      },
    ],
  },
  {
    id: 'scn-day-st-a2-01',
    level: 'A2',
    context: 'small talk',
    title: 'Gặp lại bạn cũ',
    turns: [
      {
        speakerLine: 'Oh hi! It has been such a long time.',
        speakerLineVi: 'Ồ chào bạn! Đã rất lâu rồi nhỉ.',
        answers: [{ ids: ['day-st-a2-01'] }],
        replyLine: 'I am doing well, thanks for asking.',
        replyLineVi: 'Tôi vẫn ổn, cảm ơn bạn đã hỏi.',
      },
      {
        speakerLine: 'Yeah, I moved to a new office last year.',
        speakerLineVi: 'Ừ, tôi đã chuyển đến văn phòng mới năm ngoái.',
        answers: [{ ids: ['day-st-a2-28'] }],
        replyLine: 'Oh right, I remember now!',
        replyLineVi: 'Ồ đúng rồi, giờ tôi nhớ rồi!',
      },
      {
        speakerLine: 'How have you been spending your free time?',
        speakerLineVi: 'Bạn dành thời gian rảnh thế nào?',
        answers: [{ ids: ['day-st-a2-29'] }, { ids: ['day-st-a2-30'] }],
        replyLine: 'That sounds really interesting.',
        replyLineVi: 'Nghe thật thú vị.',
      },
      {
        speakerLine: 'I should get back to work now. Great to see you!',
        speakerLineVi: 'Giờ tôi phải quay lại làm việc. Rất vui được gặp bạn!',
        answers: [{ ids: ['day-st-a2-04'] }],
        replyLine: 'Same here, see you around!',
        replyLineVi: 'Tôi cũng vậy, hẹn gặp bạn!',
      },
    ],
  },
  {
    id: 'scn-day-st-a2-02',
    level: 'A2',
    context: 'small talk',
    title: 'Trò chuyện ở quán cà phê',
    turns: [
      {
        speakerLine: 'Wow, the weather is perfect today.',
        speakerLineVi: 'Chà, hôm nay thời tiết thật đẹp.',
        answers: [{ ids: ['day-st-a2-27'] }],
        replyLine: 'It really is, perfect for a walk.',
        replyLineVi: 'Đúng vậy, hoàn hảo để đi dạo.',
      },
      {
        speakerLine: 'Would you like something to drink?',
        speakerLineVi: 'Bạn có muốn uống gì không?',
        answers: [{ ids: ['day-st-a2-32'] }, { ids: ['day-st-a2-03'] }],
        replyLine: 'Glad you like it.',
        replyLineVi: 'Rất vui vì bạn thích.',
      },
      {
        speakerLine: 'By the way, did you see the new park downtown?',
        speakerLineVi: 'Nhân tiện, bạn có thấy công viên mới ở trung tâm không?',
        answers: [{ ids: ['day-st-a2-02'] }],
        replyLine: 'Not yet, but I will check it out.',
        replyLineVi: 'Chưa, nhưng tôi sẽ ghé xem.',
      },
    ],
  },
  {
    id: 'scn-day-st-a2-03',
    level: 'A2',
    context: 'small talk',
    title: 'Chia tay sau buổi gặp',
    turns: [
      {
        speakerLine: 'I really like the shoes you are wearing today.',
        speakerLineVi: 'Tôi rất thích đôi giày bạn đang đi hôm nay.',
        answers: [{ ids: ['day-st-a2-31'] }],
        replyLine: 'Thank you, they are new.',
        replyLineVi: 'Cảm ơn, chúng là đồ mới.',
      },
      {
        speakerLine: 'Tell me more about what you enjoy doing.',
        speakerLineVi: 'Kể cho tôi thêm về điều bạn thích làm.',
        answers: [{ ids: ['day-st-a2-30'] }],
        replyLine: 'That sounds like fun!',
        replyLineVi: 'Nghe có vẻ vui đấy!',
      },
      {
        speakerLine: 'I hope we can talk again soon.',
        speakerLineVi: 'Tôi hy vọng chúng ta có thể nói chuyện lại sớm.',
        answers: [{ ids: ['day-st-a2-33'] }, { ids: ['day-st-a2-34'] }],
        replyLine: 'Absolutely, let us do that.',
        replyLineVi: 'Chắc chắn rồi, hãy làm vậy.',
      },
    ],
  },
  {
    id: 'scn-day-st-a2-04',
    level: 'A2',
    context: 'small talk',
    title: 'Mở chuyện với đồng nghiệp mới',
    turns: [
      {
        speakerLine: 'Hi, you must be the new team member!',
        speakerLineVi: 'Chào, chắc bạn là thành viên mới của nhóm!',
        answers: [{ ids: ['day-st-a2-01'] }],
        replyLine: 'Yes, I just joined this week.',
        replyLineVi: 'Vâng, tôi mới gia nhập tuần này.',
      },
      {
        speakerLine: 'The team is really friendly here.',
        speakerLineVi: 'Nhóm ở đây rất thân thiện.',
        answers: [{ ids: ['day-st-a2-03'] }],
        replyLine: 'Good to know, thanks!',
        replyLineVi: 'Biết vậy là tốt rồi, cảm ơn!',
      },
      {
        speakerLine: 'We should grab coffee together sometime.',
        speakerLineVi: 'Thỉnh thoảng chúng ta nên đi uống cà phê cùng nhau.',
        answers: [{ ids: ['day-st-a2-34'] }, { ids: ['day-st-a2-33'] }],
        replyLine: 'Sure, I would love that.',
        replyLineVi: 'Chắc chắn rồi, tôi rất muốn.',
      },
    ],
  },
  {
    id: 'scn-biz-meet-a2-01',
    level: 'A2',
    context: 'meeting',
    title: 'Họp ngân sách',
    turns: [
      {
        speakerLine: 'Good morning everyone, thank you for coming today.',
        speakerLineVi: 'Chào buổi sáng mọi người, cảm ơn đã đến hôm nay.',
        answers: [{ ids: ['biz-meet-a2-01'] }],
        replyLine: 'Happy to be here.',
        replyLineVi: 'Rất vui được tham gia.',
      },
      {
        speakerLine: 'Today we will discuss the numbers for this quarter.',
        speakerLineVi: 'Hôm nay chúng ta sẽ bàn về các con số của quý này.',
        answers: [{ ids: ['biz-meet-a2-27'] }],
        replyLine: 'Understood, let us begin.',
        replyLineVi: 'Đã rõ, hãy bắt đầu.',
      },
      {
        speakerLine: 'What would you like to look at first?',
        speakerLineVi: 'Bạn muốn xem xét gì trước?',
        answers: [{ ids: ['biz-meet-a2-29'] }],
        replyLine: 'Good idea, let us review those numbers.',
        replyLineVi: 'Ý hay, hãy xem lại những con số đó.',
      },
      {
        speakerLine: 'We have some money left for next month.',
        speakerLineVi: 'Chúng ta còn một ít tiền cho tháng sau.',
        answers: [{ ids: ['biz-meet-a2-31'] }],
        replyLine: 'That is good news.',
        replyLineVi: 'Đó là tin tốt.',
      },
    ],
  },
  {
    id: 'scn-biz-meet-a2-02',
    level: 'A2',
    context: 'meeting',
    title: 'Rà soát doanh số tháng',
    turns: [
      {
        speakerLine: 'Let us start the sales review meeting.',
        speakerLineVi: 'Hãy bắt đầu cuộc họp rà soát doanh số.',
        answers: [{ ids: ['biz-meet-a2-28'] }],
        replyLine: 'Yes, I have the numbers ready.',
        replyLineVi: 'Vâng, tôi đã chuẩn bị số liệu.',
      },
      {
        speakerLine: 'Where should we focus our attention?',
        speakerLineVi: 'Chúng ta nên tập trung vào đâu?',
        answers: [{ ids: ['biz-meet-a2-30'] }],
        replyLine: 'Good point, the customers matter most.',
        replyLineVi: 'Ý hay, khách hàng quan trọng nhất.',
      },
      {
        speakerLine: 'How is the performance this month?',
        speakerLineVi: 'Kết quả tháng này thế nào?',
        answers: [{ ids: ['biz-meet-a2-32'] }],
        replyLine: 'I see, we will need to work harder.',
        replyLineVi: 'Tôi hiểu rồi, chúng ta sẽ cần làm việc chăm hơn.',
      },
      {
        speakerLine: 'Thank you for your time, the meeting is over.',
        speakerLineVi: 'Cảm ơn thời gian của các bạn, cuộc họp kết thúc.',
        answers: [{ ids: ['biz-meet-a2-04'] }],
        replyLine: 'See you next time.',
        replyLineVi: 'Hẹn gặp lần sau.',
      },
    ],
  },
  {
    id: 'scn-biz-meet-a2-03',
    level: 'A2',
    context: 'meeting',
    title: 'Đóng góp ý kiến',
    turns: [
      {
        speakerLine: 'Here is the agenda for today.',
        speakerLineVi: 'Đây là chương trình làm việc hôm nay.',
        answers: [{ ids: ['biz-meet-a2-02'] }],
        replyLine: 'Okay, I will follow along.',
        replyLineVi: 'Được, tôi sẽ theo dõi.',
      },
      {
        speakerLine: 'I have an idea about the pricing.',
        speakerLineVi: 'Tôi có một ý tưởng về giá cả.',
        answers: [{ ids: ['biz-meet-a2-03'] }],
        replyLine: 'Please share it with us.',
        replyLineVi: 'Hãy chia sẻ với chúng tôi.',
      },
      {
        speakerLine: 'We will now talk about the monthly costs.',
        speakerLineVi: 'Giờ chúng ta sẽ nói về chi phí hàng tháng.',
        answers: [{ ids: ['biz-meet-a2-29'] }],
        replyLine: 'Great, I have the report here.',
        replyLineVi: 'Tuyệt, tôi có báo cáo ở đây.',
      },
      {
        speakerLine: 'Thank you all for the great discussion.',
        speakerLineVi: 'Cảm ơn tất cả vì buổi thảo luận tuyệt vời.',
        answers: [{ ids: ['biz-meet-a2-04'] }],
        replyLine: 'Thank you for leading it.',
        replyLineVi: 'Cảm ơn bạn đã điều phối.',
      },
    ],
  },
  {
    id: 'scn-biz-meet-a2-04',
    level: 'A2',
    context: 'meeting',
    title: 'Họp tổng kết tháng',
    turns: [
      {
        speakerLine: 'Hello everyone, let us get started.',
        speakerLineVi: 'Chào mọi người, chúng ta bắt đầu nhé.',
        answers: [{ ids: ['biz-meet-a2-01'] }],
        replyLine: 'Ready when you are.',
        replyLineVi: 'Sẵn sàng khi bạn bắt đầu.',
      },
      {
        speakerLine: 'First, let us look at the sales numbers.',
        speakerLineVi: 'Đầu tiên, hãy nhìn vào số liệu doanh số.',
        answers: [{ ids: ['biz-meet-a2-28'] }],
        replyLine: 'I prepared the summary.',
        replyLineVi: 'Tôi đã chuẩn bị bản tóm tắt.',
      },
      {
        speakerLine: 'Does anyone have questions about the customers?',
        speakerLineVi: 'Có ai có câu hỏi về khách hàng không?',
        answers: [{ ids: ['biz-meet-a2-03'] }, { ids: ['biz-meet-a2-30'] }],
        replyLine: 'Okay, we will cover that next.',
        replyLineVi: 'Được, chúng ta sẽ đề cập sau.',
      },
      {
        speakerLine: 'We are done for today, thank you!',
        speakerLineVi: 'Hôm nay đến đây thôi, cảm ơn các bạn!',
        answers: [{ ids: ['biz-meet-a2-04'] }],
        replyLine: 'Thank you, have a good day.',
        replyLineVi: 'Cảm ơn, chúc một ngày tốt lành.',
      },
    ],
  },
  {
    id: 'scn-day-work-b1-01',
    level: 'B1',
    context: 'daily work',
    title: 'Bắt đầu ngày làm việc',
    turns: [
      {
        speakerLine: 'So, what is the plan for today?',
        speakerLineVi: 'Vậy, kế hoạch hôm nay là gì?',
        answers: [{ ids: ['day-work-b1-22'] }, { ids: ['day-work-b1-23'] }],
        replyLine: 'No problem, we will manage.',
        replyLineVi: 'Không sao, chúng ta sẽ xoay xở được.',
      },
      {
        speakerLine: 'When do you usually start working?',
        speakerLineVi: 'Bạn thường bắt đầu làm việc lúc nào?',
        answers: [{ ids: ['day-work-b1-01'] }],
        replyLine: 'That sounds like a good routine.',
        replyLineVi: 'Nghe có vẻ là một thói quen tốt.',
      },
      {
        speakerLine: 'What are you working on right now?',
        speakerLineVi: 'Bạn đang làm gì bây giờ?',
        answers: [{ ids: ['day-work-b1-24'] }],
        replyLine: 'Great, keep me posted.',
        replyLineVi: 'Tuyệt, cập nhật cho tôi nhé.',
      },
      {
        speakerLine: 'Should we start with the report or the emails?',
        speakerLineVi: 'Chúng ta nên bắt đầu với báo cáo hay email?',
        answers: [{ ids: ['day-work-b1-05'] }],
        replyLine: 'Alright, let us do that.',
        replyLineVi: 'Được rồi, hãy làm vậy.',
      },
    ],
  },
  {
    id: 'scn-day-work-b1-02',
    level: 'B1',
    context: 'daily work',
    title: 'Kết thúc ngày làm việc',
    turns: [
      {
        speakerLine: 'I have a lot of small things to do after work.',
        speakerLineVi: 'Tôi có nhiều việc vặt phải làm sau giờ làm.',
        answers: [{ ids: ['day-work-b1-02'] }],
        replyLine: 'Do not forget to rest too!',
        replyLineVi: 'Đừng quên nghỉ ngơi nhé!',
      },
      {
        speakerLine: 'Should we finish the remaining tasks now?',
        speakerLineVi: 'Chúng ta có nên hoàn thành các việc còn lại bây giờ không?',
        answers: [{ ids: ['day-work-b1-04'] }],
        replyLine: 'Good, let us do it quickly.',
        replyLineVi: 'Tốt, hãy làm nhanh nào.',
      },
      {
        speakerLine: 'I think we can stop working for today.',
        speakerLineVi: 'Tôi nghĩ chúng ta có thể dừng làm việc hôm nay.',
        answers: [{ ids: ['day-work-b1-03'] }, { ids: ['day-work-b1-04'] }],
        replyLine: 'Agreed, see you tomorrow.',
        replyLineVi: 'Đồng ý, hẹn gặp ngày mai.',
      },
    ],
  },
  {
    id: 'scn-biz-email-b1-01',
    level: 'B1',
    context: 'email',
    title: 'Email nhắc việc',
    turns: [
      {
        speakerLine: 'How should we open the email to our client?',
        speakerLineVi: 'Chúng ta nên mở đầu email cho khách hàng thế nào?',
        answers: [{ ids: ['biz-email-b1-01'] }],
        replyLine: 'Good, that sounds professional.',
        replyLineVi: 'Tốt, nghe có vẻ chuyên nghiệp.',
      },
      {
        speakerLine: 'They still have not replied to our last email.',
        speakerLineVi: 'Họ vẫn chưa trả lời email trước của chúng ta.',
        answers: [{ ids: ['biz-email-b1-02'] }],
        replyLine: 'Good idea, send it today.',
        replyLineVi: 'Ý hay, hãy gửi hôm nay.',
      },
      {
        speakerLine: 'What should we say about the timeline?',
        speakerLineVi: 'Chúng ta nên nói gì về tiến độ?',
        answers: [{ ids: ['biz-email-b1-05'] }],
        replyLine: 'Perfect, that is clear.',
        replyLineVi: 'Hoàn hảo, rõ ràng đấy.',
      },
      {
        speakerLine: 'When do you need the final version?',
        speakerLineVi: 'Bạn cần bản cuối cùng khi nào?',
        answers: [{ ids: ['biz-email-b1-03'] }],
        replyLine: 'Great, I will send it soon.',
        replyLineVi: 'Tuyệt, tôi sẽ gửi sớm.',
      },
    ],
  },
  {
    id: 'scn-biz-email-b1-02',
    level: 'B1',
    context: 'email',
    title: 'Email xác nhận hợp tác',
    turns: [
      {
        speakerLine: 'We need to contact our partner about the contract.',
        speakerLineVi: 'Chúng ta cần liên hệ với đối tác về hợp đồng.',
        answers: [{ ids: ['biz-email-b1-23'] }],
        replyLine: 'Good, they will appreciate it.',
        replyLineVi: 'Tốt, họ sẽ đánh giá cao.',
      },
      {
        speakerLine: 'How do we confirm that they got our message?',
        speakerLineVi: 'Làm sao để xác nhận họ đã nhận tin nhắn của chúng ta?',
        answers: [{ ids: ['biz-email-b1-24'] }, { ids: ['biz-email-b1-06'] }],
        replyLine: 'That is exactly what we need.',
        replyLineVi: 'Đó chính xác là điều chúng ta cần.',
      },
      {
        speakerLine: 'What should we say at the end of the email?',
        speakerLineVi: 'Chúng ta nên nói gì ở cuối email?',
        answers: [{ ids: ['biz-email-b1-04'] }],
        replyLine: 'Perfect, that closes it nicely.',
        replyLineVi: 'Hoàn hảo, kết thúc gọn gàng.',
      },
    ],
  },
  {
    id: 'scn-it-meet-b2-02',
    level: 'B2',
    context: 'meeting',
    title: 'Chuẩn bị backlog',
    turns: [
      {
        speakerLine: 'We need to get the backlog ready for the next sprint.',
        speakerLineVi: 'Chúng ta cần chuẩn bị backlog cho sprint tới.',
        answers: [{ ids: ['it-meet-b2-31'] }],
        replyLine: 'Agreed, let us schedule it.',
        replyLineVi: 'Đồng ý, hãy lên lịch.',
      },
      {
        speakerLine: 'How do we decide what is ready to start?',
        speakerLineVi: 'Làm sao để quyết định việc nào sẵn sàng bắt đầu?',
        answers: [{ ids: ['it-meet-b2-33'] }],
        replyLine: 'That is the right way to decide.',
        replyLineVi: 'Đó là cách đúng để quyết định.',
      },
      {
        speakerLine: 'Let us also review our performance numbers.',
        speakerLineVi: 'Chúng ta cũng hãy xem lại các chỉ số hiệu suất.',
        answers: [{ ids: ['it-meet-b2-32'] }],
        replyLine: 'Good idea, data will help us.',
        replyLineVi: 'Ý hay, dữ liệu sẽ giúp chúng ta.',
      },
    ],
  },
  {
    id: 'scn-it-meet-b1-03',
    level: 'B1',
    context: 'meeting',
    title: 'Chuẩn bị buổi demo',
    turns: [
      {
        speakerLine: 'When is the demo for the stakeholders?',
        speakerLineVi: 'Buổi demo cho các bên liên quan diễn ra khi nào?',
        answers: [{ ids: ['it-meet-b1-31'] }],
        replyLine: 'Great, we will be ready by then.',
        replyLineVi: 'Tuyệt, chúng tôi sẽ sẵn sàng lúc đó.',
      },
      {
        speakerLine: 'Let me show you what we have done so far.',
        speakerLineVi: 'Để tôi cho bạn xem những gì chúng ta đã làm.',
        answers: [{ ids: ['it-meet-b1-32'] }],
        replyLine: 'Very helpful, thank you.',
        replyLineVi: 'Rất hữu ích, cảm ơn bạn.',
      },
      {
        speakerLine: 'Anything still blocked on our side?',
        speakerLineVi: 'Còn gì bị chặn về phía chúng ta không?',
        answers: [{ ids: ['it-meet-b1-35'] }],
        replyLine: 'Good to hear, keep me updated.',
        replyLineVi: 'Mừng vì nghe vậy, cập nhật cho tôi nhé.',
      },
      {
        speakerLine: 'Let us wrap up with the action items.',
        speakerLineVi: 'Hãy kết thúc với các việc cần làm.',
        answers: [{ ids: ['it-meet-b1-36'] }],
        replyLine: 'Perfect, we will handle them.',
        replyLineVi: 'Hoàn hảo, chúng tôi sẽ xử lý.',
      },
    ],
  },
];
